version: 2
updates:
  # Python dependencies via Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dovidio"
    assignees:
      - "dovidio"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dovidio"
    assignees:
      - "dovidio"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
