version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "colino-backend"
s3_bucket = ""  # Set via environment variable SAM_S3_BUCKET
s3_prefix = "colino-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
# Remove parameter_overrides - we'll pass them via command line
