AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'YouTube OAuth Proxy Lambda Functions'

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        GOOGLE_CLIENT_ID: !Ref GoogleClientId
        GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    NoEcho: true
  
  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    NoEcho: true
  
  AllowedOrigins:
    Type: String
    Default: 'http://localhost:3000'
    Description: Comma-separated list of allowed CORS origins

Resources:
  # Lambda function for OAuth initiation
  AuthInitiateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: package/out/lambda.zip
      Handler: lambdas.auth_initiate.lambda_handler
      Environment:
        Variables:
          ALLOWED_ORIGINS: !Ref AllowedOrigins
      Events:
        AuthInitiate:
          Type: Api
          Properties:
            Path: /auth/initiate
            Method: get

  # Lambda function for OAuth callback
  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: package/out/lambda.zip
      Handler: lambdas.auth_callback.lambda_handler
      Environment:
        Variables:
          ALLOWED_ORIGINS: !Ref AllowedOrigins
      Events:
        AuthCallback:
          Type: Api
          Properties:
            Path: /callback
            Method: get

Outputs:
  AuthInitiateApi:
    Description: "API Gateway endpoint URL for OAuth initiation"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/initiate"
  
  AuthCallbackApi:
    Description: "API Gateway endpoint URL for OAuth callback"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/callback"
